Update plot_bmh.py
Fix:
AttributeError: 'Polygon' object has no property 'normed'
Change in line 13: 'normed=True' to 'density=True' fix the AttributeError